hyperparams:
    lr: [0.01, 0.001, 0.0001]
    model:
        - { "dnn_hidden_units": [128, 128], "embedding_dim": 8, "cross_num": 2 }
        - { "dnn_hidden_units": [128, 128], "embedding_dim": 8, "cross_num": 4 }
        - {
              "dnn_hidden_units": [128, 128],
              "embedding_dim": 16,
              "cross_num": 2,
          }
        - {
              "dnn_hidden_units": [128, 128],
              "embedding_dim": 16,
              "cross_num": 4,
          }
    features:
        - {
              "numerical": [],
              "categorical": ['user_id', 'item_id']
          }
data:
    name: ML100K
    data_dir: 'data/'
    apply_fillnan: True
    apply_preprocessing: True
    random_seed: 42
    
optimizer: "SGD"
epochs: 100
random_seed: 42
